//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageGallary.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Image
    {
        public Image()
        {
            this.Comments = new HashSet<Comment>();
            this.Tags = new HashSet<Tag>();
        }

        [ScaffoldColumn(false)]
        public int ImageId { get; set; }
        [Display(Name = "Image Title")]
        [Required]
        public string ImageTitle { get; set; }
        //[RemoteClientServer("IsOrderNoAvailable", "Admin", ErrorMessage = "order no already in use")]
        [Required]
        [Display(Name = "Sequence number")]
        public int OrderNo { get; set; }
        [Display(Name = "Upload Image")]
        public string Url { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        [Display(Name = "Upload date"), DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> UploadDate { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
