//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace ImageGallary.Models
{

    public partial class Tag
    {
        [ScaffoldColumn(false)]
        public int TagId { get; set; }
        [ScaffoldColumn(false)]
        public int ImageId { get; set; }
        [Display(Name = "Tag")]
        [Required]
        public string TagText { get; set; }
        [Display(Name = "Upload date"), DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public System.DateTime TagDate { get; set; }
        public int UserId { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
