//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageGallary.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserDetail
    {
        public UserDetail()
        {
            this.Comments = new HashSet<Comment>();
            this.Tags = new HashSet<Tag>();
        }

        [ScaffoldColumn(false)]
        public int Id { get; set; }
        [Display(Name = "First name")]
        [Required]
        public string Firstname { get; set; }
        [Display(Name = "Last name")]
        [Required]
        public string Lastname { get; set; }
        [Required]
        [RegularExpression(@"^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$", ErrorMessage = "Email address should be in the format abc@domain.com")]
        public string Email { get; set; }
        [Required]
        [DataType(DataType.Password, ErrorMessage = "Invalid password")]
        [RegularExpression("^(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=]).{8,16}$", ErrorMessage = "Password contains one special character, one uppercase, one lowercase, minimum 8 and maximum 16 characters")]
        public string Password { get; set; }
        [Compare("Password")]
        public string ConfirmPassword { get; set; }
        public short UsertypeId { get; set; }
        [Display(Name = "Registration Date")]
        public Nullable<System.DateTime> RegistrationDate { get; set; }

        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Usertype Usertype { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
